#!/usr/bin/env python3
"""Restricted replay runner (issue #20, second tranche).

Replays the SOURCE PROOF of an explicit relative theorem in a sandbox, then ties the
replay to the original by exact statement agreement and checks the replay's total
dependency closure against a declared boundary. Provenance is bound to what this runner
itself compiled.

What a passing run certifies, precisely:
  1. fresh compilation — the sandbox source (the fixture's source text with its import
     block REPLACED by the plan's approved imports and its namespace renamed) compiled
     from scratch, in this run, with exactly those imports;
  2. source-proof replay — the replayed declarations are the source's own proofs,
     elaborated afresh; they are distinct constants, never the original ones (the
     original module is forbidden to the replay by its boundary);
  3. exact statement agreement — the replayed target's statement is syntactically
     identical to the original's (`#rm_assert_same_statement`);
  4. the complete declaration-boundary check on the replay (`#rm_check_boundary`,
     total closure, standard-axiom policy enforced);
  5. provenance bound to the compiled artifact — sha256 of the plan, of the sandbox
     source this runner wrote, and of the .olean this runner produced and then loaded
     for the checks (compile and load happen in one run, on paths this runner owns).

What it does NOT certify: fragment membership in any object theory, a weak-system
interpretation, nonstandard-model transport, or any reverse-mathematical bound.
Import restrictions are enforced here (the sandbox imports exactly the approved list);
declaration restrictions by the boundary checker.
"""
from __future__ import annotations
import argparse, hashlib, json, os, re, shutil, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPLAY_DIR = ROOT / ".lake" / "build" / "replay"

def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()

def run(cmd: list[str], env: dict | None = None, cwd: Path = ROOT) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, env=env, capture_output=True, text=True)

def lean_path() -> str:
    r = run(["lake", "env", "printenv", "LEAN_PATH"])
    if r.returncode != 0:
        raise SystemExit(f"replay: cannot read LEAN_PATH: {r.stderr}")
    return r.stdout.strip()

IMPORT_RE = re.compile(r"^import\s+(\S+)\s*$")

def split_source(text: str) -> tuple[str, list[str], str]:
    """(header comment, imports, body) — the import block must be contiguous and precede
    everything except the leading comment."""
    lines = text.split("\n")
    header, imports, body = [], [], []
    i = 0
    if lines and lines[0].startswith("/-"):
        while i < len(lines):
            header.append(lines[i])
            if lines[i].rstrip().endswith("-/"):
                i += 1
                break
            i += 1
    while i < len(lines) and IMPORT_RE.match(lines[i]):
        imports.append(IMPORT_RE.match(lines[i]).group(1)); i += 1
    body = lines[i:]
    for ln in body:
        if IMPORT_RE.match(ln):
            raise SystemExit("replay: an import outside the leading import block; refusing")
    return "\n".join(header), imports, "\n".join(body)

def make_sandbox_source(plan: dict, source: str) -> str:
    header, _orig_imports, body = split_source(source)
    for old, new in plan["namespaceMap"].items():
        body = body.replace(old, new)
    imports = "\n".join(f"import {m}" for m in plan["approvedImports"])
    banner = (f"/-! Restricted replay sandbox — generated by scripts/replay.py from "
              f"{plan['sourcePath']} under plan {plan['id']}; imports are exactly the "
              f"approved list; namespace renamed per the plan. Never edit by hand. -/")
    return f"{header}\n{imports}\n\n{banner}\n{body}"

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("plan", nargs="?")
    ap.add_argument("--selftest", action="store_true", help="run the rejection fixtures")
    ap.add_argument("--json", action="store_true", help="emit the record as JSON only")
    args = ap.parse_args()
    if args.selftest:
        return selftest()
    if not args.plan:
        ap.error("plan required")
    record = replay(json.loads(Path(args.plan).read_text()), verbose=not args.json)
    print(json.dumps(record, indent=1) if args.json else render(record))
    return 0

def replay(plan: dict, verbose: bool = True, work: Path | None = None) -> dict:
    work = work or REPLAY_DIR / plan["id"]
    if work.exists():
        shutil.rmtree(work)
    src_dir, lib_dir = work / "src", work / "lib"
    src_dir.mkdir(parents=True); lib_dir.mkdir(parents=True)
    # 0. the plan's imports are the only imports: refuse anything the plan does not name
    #    among what the SOURCE needs is discovered by compilation; anything the plan names
    #    outside its own approved list is impossible by construction. Reject a plan whose
    #    approved list names a module the boundary forbids? — that is the boundary's job;
    #    here we only refuse malformed plans.
    for key in ("id", "sourcePath", "sourceModule", "replayModule", "namespaceMap",
                "approvedImports", "target", "replayTarget", "boundaryModule", "boundary"):
        if key not in plan:
            raise SystemExit(f"replay: plan lacks '{key}'")
    source_path = ROOT / plan["sourcePath"]
    source = source_path.read_text()
    sandbox = make_sandbox_source(plan, source)
    mod_parts = plan["replayModule"].split(".")
    src_file = src_dir.joinpath(*mod_parts).with_suffix(".lean")
    src_file.parent.mkdir(parents=True, exist_ok=True)
    src_file.write_text(sandbox)
    olean = lib_dir.joinpath(*mod_parts).with_suffix(".olean")
    ilean = olean.with_suffix(".ilean")
    olean.parent.mkdir(parents=True, exist_ok=True)
    # 1. fresh compilation with exactly the approved imports
    env = dict(os.environ); env["LEAN_PATH"] = lean_path()
    r = run(["lean", str(src_file), "-o", str(olean), "-i", str(ilean)], env=env)
    if r.returncode != 0:
        raise SystemExit(f"replay: fresh compilation FAILED under the approved imports:\n"
                         f"{r.stdout[-4000:]}\n{r.stderr[-4000:]}")
    olean_bytes = olean.read_bytes()
    # 2–4. statement agreement and boundary check, loading the olean this run produced
    check = work / "Check.lean"
    check.write_text("\n".join([
        f"import {plan['sourceModule']}",
        f"import {plan['replayModule']}",
        f"import {plan['boundaryModule']}",
        "set_option rm.maxNodes 800000",
        f"#rm_assert_same_statement {plan['target']} {plan['replayTarget']}",
        f"#rm_check_boundary {plan['replayTarget']} {plan['boundary']}",
        ""]))
    env2 = dict(env); env2["LEAN_PATH"] = f"{lib_dir}:{env['LEAN_PATH']}"
    r2 = run(["lean", str(check)], env=env2)
    ok = r2.returncode == 0 and "error" not in (r2.stdout + r2.stderr)
    if not ok:
        raise SystemExit(f"replay: checks FAILED:\n{r2.stdout[-4000:]}\n{r2.stderr[-4000:]}")
    # 5. provenance bound to what this run compiled and loaded
    git = run(["git", "rev-parse", "HEAD"]).stdout.strip()
    lean_v = run(["lean", "--version"]).stdout.strip()
    return {
        "kind": "restrictedReplay",
        "plan": plan["id"], "planSha256": sha256(json.dumps(plan, sort_keys=True).encode()),
        "sourcePath": plan["sourcePath"], "sourceSha256": sha256(source.encode()),
        "sandboxSourceSha256": sha256(sandbox.encode()),
        "approvedImports": plan["approvedImports"],
        "compiledOleanSha256": sha256(olean_bytes), "compiledOleanBytes": len(olean_bytes),
        "target": plan["target"], "replayTarget": plan["replayTarget"],
        "boundary": plan["boundary"],
        "checkOutput": (r2.stdout + r2.stderr).strip(),
        "environment": {"lean": lean_v, "gitRevision": git,
                         "note": "compile and load happened in this run on paths the "
                                 "runner owns; the olean hash is of the file produced "
                                 "here and loaded for the checks"},
        "certifies": ["fresh compilation with exactly the approved imports",
                       "source-proof replay (distinct constants)",
                       "exact statement agreement", "declaration boundary on the total "
                       "closure with the standard-axiom policy"],
        "doesNotCertify": ["fragment membership in any object theory",
                            "weak-system interpretation", "nonstandard-model transport",
                            "any reverse-mathematical bound"],
    }

def render(rec: dict) -> str:
    out = [f"restricted replay {rec['plan']}: PASS",
           f"  source {rec['sourcePath']} sha256 {rec['sourceSha256'][:16]}…; sandbox "
           f"sha256 {rec['sandboxSourceSha256'][:16]}…; plan sha256 {rec['planSha256'][:16]}…",
           f"  approved imports: {', '.join(rec['approvedImports'])}",
           f"  compiled olean sha256 {rec['compiledOleanSha256'][:16]}… "
           f"({rec['compiledOleanBytes']} bytes), loaded for the checks in this run",
           f"  {rec['environment']['lean']}; git {rec['environment']['gitRevision'][:12]}",
           "  checks:"]
    out += ["    " + ln for ln in rec["checkOutput"].split("\n")]
    out += ["  does not certify: " + "; ".join(rec["doesNotCertify"])]
    return "\n".join(out)

# ---------------------------------------------------------------- rejection fixtures
def selftest() -> int:
    base = json.loads((ROOT / "scripts/replay/plan_hall.json").read_text())
    failures = []
    def expect_fail(name: str, plan: dict, reason: str, mutate_source: str | None = None):
        """The fixture must be rejected, and for the stated reason (a substring of the
        runner's message) — a rejection for a different reason does not count."""
        p = dict(plan); p["id"] = f"selftest.{name}"
        work = REPLAY_DIR / p["id"]
        try:
            if mutate_source is not None:
                mp = REPLAY_DIR / f"{p['id']}.src.lean"
                mp.parent.mkdir(parents=True, exist_ok=True)
                mp.write_text(mutate_source); p["sourcePath"] = str(mp.relative_to(ROOT))
            replay(p, verbose=False, work=work)
        except SystemExit as e:
            msg = str(e)
            if reason in msg:
                print(f"selftest {name}: rejected for the required reason ({reason!r})")
            else:
                failures.append(name)
                print(f"selftest {name}: rejected but NOT for {reason!r}:\n"
                      + "\n".join("    " + l for l in msg.splitlines()[:6]))
            return
        failures.append(name); print(f"selftest {name}: NOT rejected")
    src = (ROOT / base["sourcePath"]).read_text()
    thm = "theorem countableHall_of_finiteInverseLimitCompactness\n    (hcompact : ExplicitFiniteInverseLimitCompactness) : CountableHall := by\n"
    assert thm in src, "fixture theorem header changed; update the selftest"
    # (a) an import the source needs is missing from the approved list: fresh compilation
    #     fails — import restriction is enforced by construction
    p = dict(base); p["approvedImports"] = [m for m in base["approvedImports"]
                                            if m != "Mathlib.Combinatorics.Hall.Finite"]
    expect_fail("missing-approved-import", p, "fresh compilation FAILED")
    # (b) statement drift: the replay target is a different theorem
    p = dict(base); p["replayTarget"] = "ReverseMathlibReplay.Slice.mem_transversalLists"
    expect_fail("statement-drift", p, "not syntactically identical")
    # (c) boundary violation with the statement intact: the source proof is mutated to
    #     touch mathlib's infinite Hall theorem under a plan approving its module —
    #     compiles, statements agree, the boundary rejects it by name
    mutated = src.replace(thm, thm + "  have _forbidden := @Finset.all_card_le_biUnion_card_iff_exists_injective.{0, 0}\n", 1)
    mutated = mutated.replace("assert_not_exists Finset.all_card_le_biUnion_card_iff_exists_injective\n", "")
    p = dict(base); p["approvedImports"] = base["approvedImports"] + ["Mathlib.Combinatorics.Hall.Basic"]
    expect_fail("boundary-violation", p, "forbidden declaration", mutated)
    # (d) a "replay" that reaches the ORIGINAL module instead of replaying: the plan
    #     approves the original module and the proof delegates to the original theorem —
    #     compiles, statements agree, the boundary rejects the original module
    #     (the proof is kept intact so its enumerated auxiliaries still exist; it merely
    #     touches an original helper, named with guillemets so the plan's textual
    #     namespace rename leaves the reference pointing at the ORIGINAL module)
    mutated2 = src.replace(thm, thm + "  have _original := «ReverseMathlib».Slice.decodeList\n", 1)
    p = dict(base); p["approvedImports"] = base["approvedImports"] + ["ReverseMathlib.Slice.HallFromCompactness"]
    expect_fail("reaches-original-module", p, "forbidden module ReverseMathlib.Slice.HallFromCompactness", mutated2)
    # (e) tampering: the plan's approved list is not what the sandbox imported — impossible
    #     by construction (the sandbox import block is generated from the plan), recorded
    #     here as a property, not a fixture
    if failures:
        print(f"replay selftest: {len(failures)} fixture(s) failed: {failures}"); return 1
    print("replay selftest: all rejection fixtures rejected for their stated reasons"); return 0

if __name__ == "__main__":
    sys.exit(main())
